Sprint7
ClevertecFrontendLab/tsakunova pull request #5
Opened 2023-03-25 10:57 UTC by tsakunova

2023-03-25 11:12 UTC, Rastamanby commented
#  Результаты тестов
Процент пройденных тестов: 98%.
Общее количество тестов: 98.
Количество непройденных тестов: 1.
***
**1-slider-no-photo-1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/tsakunova/1679742763/1-slider-no-photo-1440px.png)
***
**1-slider-no-photo-320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/tsakunova/1679742763/1-slider-no-photo-320px.png)
***
**10-app-burger-menu-close-click-not-burger-menu-768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/tsakunova/1679742763/10-app-burger-menu-close-click-not-burger-menu-768px.png)
***
**11-app-320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/tsakunova/1679742763/11-app-320px.png)
***
**12-app-burger-menu-open-320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/tsakunova/1679742763/12-app-burger-menu-open-320px.png)
***
**13-app-burger-menu-close-320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/tsakunova/1679742763/13-app-burger-menu-close-320px.png)
***
**14-app-burger-menu-close-click-not-burger-menu-320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/tsakunova/1679742763/14-app-burger-menu-close-click-not-burger-menu-320px.png)
***
**15-1440-profile-page.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/tsakunova/1679742763/15-1440-profile-page.png)
***
**16-768-profile-page.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/tsakunova/1679742763/16-768-profile-page.png)
***
**17-320-profile-page.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/tsakunova/1679742763/17-320-profile-page.png)
***
**18-profile-avatar-before.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/tsakunova/1679742763/18-profile-avatar-before.png)
***
**19-profile-avatar-after.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/tsakunova/1679742763/19-profile-avatar-after.png)
***
**2-slider-one-photo-1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/tsakunova/1679742763/2-slider-one-photo-1440px.png)
***
**2-slider-one-photo-768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/tsakunova/1679742763/2-slider-one-photo-768px.png)
***
**20-1440-profile-empty-card.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/tsakunova/1679742763/20-1440-profile-empty-card.png)
***
**21-1440-profile-empty-card.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/tsakunova/1679742763/21-1440-profile-empty-card.png)
***
**22-1440-profile-empty-card.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/tsakunova/1679742763/22-1440-profile-empty-card.png)
***
**23-1440-profile-expider-card.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/tsakunova/1679742763/23-1440-profile-expider-card.png)
***
**24-1440-profile-empty-card.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/tsakunova/1679742763/24-1440-profile-empty-card.png)
***
**25-1440-history.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/tsakunova/1679742763/25-1440-history.png)
***
**3-slider-more-two-photo-1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/tsakunova/1679742763/3-slider-more-two-photo-1440px.png)
***
**3-slider-more-two-photo-768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/tsakunova/1679742763/3-slider-more-two-photo-768px.png)
***
**4-slider-before-1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/tsakunova/1679742763/4-slider-before-1440px.png)
***
**4-slider-before-320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/tsakunova/1679742763/4-slider-before-320px.png)
***
**4-slider-before-768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/tsakunova/1679742763/4-slider-before-768px.png)
***
**5-slider-after-1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/tsakunova/1679742763/5-slider-after-1440px.png)
***
**6-app-1440.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/tsakunova/1679742763/6-app-1440.png)
***
**7-app-768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/tsakunova/1679742763/7-app-768px.png)
***
**8-app-burger-menu-open-768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/tsakunova/1679742763/8-app-burger-menu-open-768px.png)
***
**9-app -burger-menu-close-768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/tsakunova/1679742763/9-app%20-burger-menu-close-768px.png)
***
**Sprint 5 -- authorization and registartion -- authorization -- redirect authorization (failed).png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/tsakunova/1679742763/Sprint%205%20--%20authorization%20and%20registartion%20--%20authorization%20--%20redirect%20authorization%20(failed).png)

2023-03-25 13:34 UTC, vvikota requested changes

2023-03-25 13:34 UTC, vvikota commented on cypress.config.ts
>  export default defineConfig({
![image](https://user-images.githubusercontent.com/30027067/227719938-f9febced-bf4c-4ec8-88d8-4efcd3e30136.png)
cкачал проект и запустил:
1. имя не соответсвует реальному
2. по ТЗ тут нужна картинка котика)
3. блоков не хватает как в макете

2023-03-25 13:34 UTC, vvikota commented on cypress.config.ts
> +        experimentalSessionAndOrigin: true,
![image](https://user-images.githubusercontent.com/30027067/227720054-983baf35-34cc-4a55-8abf-230d4b9e8f53.png)
адаптивка , фотка не должна так сплющиваться)

2023-03-25 13:34 UTC, vvikota commented on cypress.config.ts
>          screenshotsFolder: "cypress/report/screenshots",
![image](https://user-images.githubusercontent.com/30027067/227720244-50ece16e-0871-485b-b9cb-e570e0d460db.png)
тут нужно сделать cursor: pointer чтобы пользователю было понятно что можно кликнуть

2023-03-25 13:39 UTC, tsakunova commented on cypress.config.ts
>  export default defineConfig({
эммм... а это точно 7 спринт вы скачали мой??

2023-03-25 13:40 UTC, tsakunova commented on cypress.config.ts
> +        experimentalSessionAndOrigin: true,
это явно или 6 спринт(я тогда начинала только профайл делать) или вообще не мое

2023-03-25 13:41 UTC, vvikota commented on cypress.config.ts
>  export default defineConfig({
> эммм... а это точно 7 спринт вы скачали мой??

секунду , перепроверю)

2023-03-25 13:45 UTC, Rastamanby commented
#  Результаты тестов
Процент пройденных тестов: 93%.
Общее количество тестов: 98.
Количество непройденных тестов: 6.
***
**1-slider-no-photo-1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/tsakunova/1679751903/1-slider-no-photo-1440px.png)
***
**1-slider-no-photo-320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/tsakunova/1679751903/1-slider-no-photo-320px.png)
***
**10-app-burger-menu-close-click-not-burger-menu-768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/tsakunova/1679751903/10-app-burger-menu-close-click-not-burger-menu-768px.png)
***
**11-app-320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/tsakunova/1679751903/11-app-320px.png)
***
**12-app-burger-menu-open-320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/tsakunova/1679751903/12-app-burger-menu-open-320px.png)
***
**13-app-burger-menu-close-320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/tsakunova/1679751903/13-app-burger-menu-close-320px.png)
***
**14-app-burger-menu-close-click-not-burger-menu-320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/tsakunova/1679751903/14-app-burger-menu-close-click-not-burger-menu-320px.png)
***
**18-profile-avatar-before.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/tsakunova/1679751903/18-profile-avatar-before.png)
***
**19-profile-avatar-after.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/tsakunova/1679751903/19-profile-avatar-after.png)
***
**2-slider-one-photo-1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/tsakunova/1679751903/2-slider-one-photo-1440px.png)
***
**2-slider-one-photo-768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/tsakunova/1679751903/2-slider-one-photo-768px.png)
***
**20-1440-profile-empty-card.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/tsakunova/1679751903/20-1440-profile-empty-card.png)
***
**21-1440-profile-empty-card.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/tsakunova/1679751903/21-1440-profile-empty-card.png)
***
**22-1440-profile-empty-card.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/tsakunova/1679751903/22-1440-profile-empty-card.png)
***
**23-1440-profile-expider-card.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/tsakunova/1679751903/23-1440-profile-expider-card.png)
***
**24-1440-profile-empty-card.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/tsakunova/1679751903/24-1440-profile-empty-card.png)
***
**25-1440-history.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/tsakunova/1679751903/25-1440-history.png)
***
**3-slider-more-two-photo-1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/tsakunova/1679751903/3-slider-more-two-photo-1440px.png)
***
**3-slider-more-two-photo-768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/tsakunova/1679751903/3-slider-more-two-photo-768px.png)
***
**4-slider-before-1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/tsakunova/1679751903/4-slider-before-1440px.png)
***
**4-slider-before-320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/tsakunova/1679751903/4-slider-before-320px.png)
***
**4-slider-before-768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/tsakunova/1679751903/4-slider-before-768px.png)
***
**5-slider-after-1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/tsakunova/1679751903/5-slider-after-1440px.png)
***
**6-app-1440.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/tsakunova/1679751903/6-app-1440.png)
***
**7-app-768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/tsakunova/1679751903/7-app-768px.png)
***
**8-app-burger-menu-open-768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/tsakunova/1679751903/8-app-burger-menu-open-768px.png)
***
**9-app -burger-menu-close-768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/tsakunova/1679751903/9-app%20-burger-menu-close-768px.png)
***
**Sprint 4 -- search and sort -- bread crumbs -- desktop -- transfer from all books category to book page (failed).png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/tsakunova/1679751903/Sprint%204%20--%20search%20and%20sort%20--%20bread%20crumbs%20--%20desktop%20--%20transfer%20from%20all%20books%20category%20to%20book%20page%20(failed).png)
***
**Sprint 4 -- search and sort -- bread crumbs -- tablet -- transfer from all books category to book page (failed).png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/tsakunova/1679751903/Sprint%204%20--%20search%20and%20sort%20--%20bread%20crumbs%20--%20tablet%20--%20transfer%20from%20all%20books%20category%20to%20book%20page%20(failed).png)
***
**Sprint 4 -- search and sort -- bread crumbs -- tablet -- transfer from programming category to book page (failed).png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/tsakunova/1679751903/Sprint%204%20--%20search%20and%20sort%20--%20bread%20crumbs%20--%20tablet%20--%20transfer%20from%20programming%20category%20to%20book%20page%20(failed).png)
***
**Sprint 5 -- authorization and registartion -- authorization -- redirect authorization (failed).png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/tsakunova/1679751903/Sprint%205%20--%20authorization%20and%20registartion%20--%20authorization%20--%20redirect%20authorization%20(failed).png)
***
**Sprint 7 -- Profile functions tests -- cancel-booking -- fail (failed).png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/tsakunova/1679751903/Sprint%207%20--%20Profile%20functions%20tests%20--%20cancel-booking%20--%20fail%20(failed).png)
***
**Sprint 7 -- profile page -- screenshots (failed).png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/tsakunova/1679751903/Sprint%207%20--%20profile%20page%20--%20screenshots%20(failed).png)

2023-03-25 13:55 UTC, vvikota commented on cypress.config.ts
>          screenshotsFolder: "cypress/report/screenshots",
верхние комменты удалил, все работает как надо)

2023-03-25 13:59 UTC, tsakunova commented on cypress.config.ts
>          screenshotsFolder: "cypress/report/screenshots",
спасибо, коменты порезолвала
вот только опять тесты падают через один(
попробую еще попозже до 100 их вытянуть(( локально проходят

2023-03-25 14:06 UTC, Rastamanby commented
#  Результаты тестов
Процент пройденных тестов: 94%.
Общее количество тестов: 98.
Количество непройденных тестов: 5.
***
**1-slider-no-photo-320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/tsakunova/1679753164/1-slider-no-photo-320px.png)
***
**10-app-burger-menu-close-click-not-burger-menu-768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/tsakunova/1679753164/10-app-burger-menu-close-click-not-burger-menu-768px.png)
***
**11-app-320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/tsakunova/1679753164/11-app-320px.png)
***
**12-app-burger-menu-open-320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/tsakunova/1679753164/12-app-burger-menu-open-320px.png)
***
**13-app-burger-menu-close-320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/tsakunova/1679753164/13-app-burger-menu-close-320px.png)
***
**14-app-burger-menu-close-click-not-burger-menu-320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/tsakunova/1679753164/14-app-burger-menu-close-click-not-burger-menu-320px.png)
***
**15-1440-profile-page.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/tsakunova/1679753164/15-1440-profile-page.png)
***
**16-768-profile-page.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/tsakunova/1679753164/16-768-profile-page.png)
***
**17-320-profile-page.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/tsakunova/1679753164/17-320-profile-page.png)
***
**18-profile-avatar-before.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/tsakunova/1679753164/18-profile-avatar-before.png)
***
**19-profile-avatar-after.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/tsakunova/1679753164/19-profile-avatar-after.png)
***
**2-slider-one-photo-1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/tsakunova/1679753164/2-slider-one-photo-1440px.png)
***
**2-slider-one-photo-768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/tsakunova/1679753164/2-slider-one-photo-768px.png)
***
**20-1440-profile-empty-card.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/tsakunova/1679753164/20-1440-profile-empty-card.png)
***
**21-1440-profile-empty-card.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/tsakunova/1679753164/21-1440-profile-empty-card.png)
***
**22-1440-profile-empty-card.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/tsakunova/1679753164/22-1440-profile-empty-card.png)
***
**23-1440-profile-expider-card.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/tsakunova/1679753164/23-1440-profile-expider-card.png)
***
**24-1440-profile-empty-card.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/tsakunova/1679753164/24-1440-profile-empty-card.png)
***
**25-1440-history.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/tsakunova/1679753164/25-1440-history.png)
***
**3-slider-more-two-photo-768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/tsakunova/1679753164/3-slider-more-two-photo-768px.png)
***
**4-slider-before-320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/tsakunova/1679753164/4-slider-before-320px.png)
***
**4-slider-before-768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/tsakunova/1679753164/4-slider-before-768px.png)
***
**6-app-1440.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/tsakunova/1679753164/6-app-1440.png)
***
**7-app-768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/tsakunova/1679753164/7-app-768px.png)
***
**8-app-burger-menu-open-768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/tsakunova/1679753164/8-app-burger-menu-open-768px.png)
***
**9-app -burger-menu-close-768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/tsakunova/1679753164/9-app%20-burger-menu-close-768px.png)
***
**Sprint 2 -- slider tests -- slider more two foto (failed).png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/tsakunova/1679753164/Sprint%202%20--%20slider%20tests%20--%20slider%20more%20two%20foto%20(failed).png)
***
**Sprint 2 -- slider tests -- test not foto (failed).png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/tsakunova/1679753164/Sprint%202%20--%20slider%20tests%20--%20test%20not%20foto%20(failed).png)
***
**Sprint 4 -- search and sort -- bread crumbs -- tablet -- transfer from all books category to book page (failed).png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/tsakunova/1679753164/Sprint%204%20--%20search%20and%20sort%20--%20bread%20crumbs%20--%20tablet%20--%20transfer%20from%20all%20books%20category%20to%20book%20page%20(failed).png)
***
**Sprint 4 -- search and sort -- bread crumbs -- tablet -- transfer from programming category to book page (failed).png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/tsakunova/1679753164/Sprint%204%20--%20search%20and%20sort%20--%20bread%20crumbs%20--%20tablet%20--%20transfer%20from%20programming%20category%20to%20book%20page%20(failed).png)
***
**Sprint 5 -- authorization and registartion -- authorization -- redirect authorization (failed).png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/tsakunova/1679753164/Sprint%205%20--%20authorization%20and%20registartion%20--%20authorization%20--%20redirect%20authorization%20(failed).png)

2023-03-25 15:09 UTC, Rastamanby commented
#  Результаты тестов
Процент пройденных тестов: 97%.
Общее количество тестов: 98.
Количество непройденных тестов: 2.
***
**1-slider-no-photo-1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/tsakunova/1679756942/1-slider-no-photo-1440px.png)
***
**1-slider-no-photo-320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/tsakunova/1679756942/1-slider-no-photo-320px.png)
***
**10-app-burger-menu-close-click-not-burger-menu-768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/tsakunova/1679756942/10-app-burger-menu-close-click-not-burger-menu-768px.png)
***
**11-app-320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/tsakunova/1679756942/11-app-320px.png)
***
**12-app-burger-menu-open-320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/tsakunova/1679756942/12-app-burger-menu-open-320px.png)
***
**13-app-burger-menu-close-320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/tsakunova/1679756942/13-app-burger-menu-close-320px.png)
***
**14-app-burger-menu-close-click-not-burger-menu-320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/tsakunova/1679756942/14-app-burger-menu-close-click-not-burger-menu-320px.png)
***
**15-1440-profile-page.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/tsakunova/1679756942/15-1440-profile-page.png)
***
**16-768-profile-page.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/tsakunova/1679756942/16-768-profile-page.png)
***
**17-320-profile-page.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/tsakunova/1679756942/17-320-profile-page.png)
***
**18-profile-avatar-before.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/tsakunova/1679756942/18-profile-avatar-before.png)
***
**19-profile-avatar-after.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/tsakunova/1679756942/19-profile-avatar-after.png)
***
**2-slider-one-photo-1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/tsakunova/1679756942/2-slider-one-photo-1440px.png)
***
**2-slider-one-photo-768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/tsakunova/1679756942/2-slider-one-photo-768px.png)
***
**20-1440-profile-empty-card.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/tsakunova/1679756942/20-1440-profile-empty-card.png)
***
**21-1440-profile-empty-card.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/tsakunova/1679756942/21-1440-profile-empty-card.png)
***
**22-1440-profile-empty-card.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/tsakunova/1679756942/22-1440-profile-empty-card.png)
***
**23-1440-profile-expider-card.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/tsakunova/1679756942/23-1440-profile-expider-card.png)
***
**24-1440-profile-empty-card.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/tsakunova/1679756942/24-1440-profile-empty-card.png)
***
**25-1440-history.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/tsakunova/1679756942/25-1440-history.png)
***
**3-slider-more-two-photo-1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/tsakunova/1679756942/3-slider-more-two-photo-1440px.png)
***
**3-slider-more-two-photo-768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/tsakunova/1679756942/3-slider-more-two-photo-768px.png)
***
**4-slider-before-1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/tsakunova/1679756942/4-slider-before-1440px.png)
***
**4-slider-before-320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/tsakunova/1679756942/4-slider-before-320px.png)
***
**4-slider-before-768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/tsakunova/1679756942/4-slider-before-768px.png)
***
**5-slider-after-1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/tsakunova/1679756942/5-slider-after-1440px.png)
***
**6-app-1440.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/tsakunova/1679756942/6-app-1440.png)
***
**7-app-768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/tsakunova/1679756942/7-app-768px.png)
***
**8-app-burger-menu-open-768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/tsakunova/1679756942/8-app-burger-menu-open-768px.png)
***
**9-app -burger-menu-close-768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/tsakunova/1679756942/9-app%20-burger-menu-close-768px.png)
***
**Sprint 5 -- authorization and registartion -- authorization -- redirect authorization (failed).png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/tsakunova/1679756942/Sprint%205%20--%20authorization%20and%20registartion%20--%20authorization%20--%20redirect%20authorization%20(failed).png)
***
**Sprint 7 -- Profile functions tests -- cancel-booking -- success (failed).png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/tsakunova/1679756942/Sprint%207%20--%20Profile%20functions%20tests%20--%20cancel-booking%20--%20success%20(failed).png)

2023-03-25 15:41 UTC, vvikota approved these changes

2023-03-25 19:16 UTC, Rastamanby commented
#  Результаты тестов
Процент пройденных тестов: 98%.
Общее количество тестов: 98.
Количество непройденных тестов: 1.
***
**1-slider-no-photo-1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/tsakunova/1679771819/1-slider-no-photo-1440px.png)
***
**1-slider-no-photo-320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/tsakunova/1679771819/1-slider-no-photo-320px.png)
***
**10-app-burger-menu-close-click-not-burger-menu-768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/tsakunova/1679771819/10-app-burger-menu-close-click-not-burger-menu-768px.png)
***
**11-app-320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/tsakunova/1679771819/11-app-320px.png)
***
**12-app-burger-menu-open-320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/tsakunova/1679771819/12-app-burger-menu-open-320px.png)
***
**13-app-burger-menu-close-320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/tsakunova/1679771819/13-app-burger-menu-close-320px.png)
***
**14-app-burger-menu-close-click-not-burger-menu-320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/tsakunova/1679771819/14-app-burger-menu-close-click-not-burger-menu-320px.png)
***
**15-1440-profile-page.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/tsakunova/1679771819/15-1440-profile-page.png)
***
**16-768-profile-page.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/tsakunova/1679771819/16-768-profile-page.png)
***
**17-320-profile-page.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/tsakunova/1679771819/17-320-profile-page.png)
***
**18-profile-avatar-before.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/tsakunova/1679771819/18-profile-avatar-before.png)
***
**19-profile-avatar-after.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/tsakunova/1679771819/19-profile-avatar-after.png)
***
**2-slider-one-photo-1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/tsakunova/1679771819/2-slider-one-photo-1440px.png)
***
**2-slider-one-photo-768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/tsakunova/1679771819/2-slider-one-photo-768px.png)
***
**20-1440-profile-empty-card.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/tsakunova/1679771819/20-1440-profile-empty-card.png)
***
**21-1440-profile-empty-card.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/tsakunova/1679771819/21-1440-profile-empty-card.png)
***
**22-1440-profile-empty-card.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/tsakunova/1679771819/22-1440-profile-empty-card.png)
***
**23-1440-profile-expider-card.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/tsakunova/1679771819/23-1440-profile-expider-card.png)
***
**24-1440-profile-empty-card.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/tsakunova/1679771819/24-1440-profile-empty-card.png)
***
**25-1440-history.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/tsakunova/1679771819/25-1440-history.png)
***
**3-slider-more-two-photo-1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/tsakunova/1679771819/3-slider-more-two-photo-1440px.png)
***
**3-slider-more-two-photo-768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/tsakunova/1679771819/3-slider-more-two-photo-768px.png)
***
**4-slider-before-1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/tsakunova/1679771819/4-slider-before-1440px.png)
***
**4-slider-before-320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/tsakunova/1679771819/4-slider-before-320px.png)
***
**4-slider-before-768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/tsakunova/1679771819/4-slider-before-768px.png)
***
**5-slider-after-1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/tsakunova/1679771819/5-slider-after-1440px.png)
***
**6-app-1440.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/tsakunova/1679771819/6-app-1440.png)
***
**7-app-768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/tsakunova/1679771819/7-app-768px.png)
***
**8-app-burger-menu-open-768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/tsakunova/1679771819/8-app-burger-menu-open-768px.png)
***
**9-app -burger-menu-close-768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/tsakunova/1679771819/9-app%20-burger-menu-close-768px.png)
***
**Sprint 5 -- authorization and registartion -- authorization -- redirect authorization (failed).png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/tsakunova/1679771819/Sprint%205%20--%20authorization%20and%20registartion%20--%20authorization%20--%20redirect%20authorization%20(failed).png)

2023-03-25 19:19 UTC, ValadzkoAliaksei commented on package.json
> +    "@types/js-cookie": "^3.0.3",
![image](https://user-images.githubusercontent.com/61273546/227737102-063a96d0-b8ca-4a86-982b-0dcf2b010dda.png)
зашел зарегистрированным пользаком, и роутинг сломан( никуда не перекидывает

2023-03-25 19:21 UTC, ValadzkoAliaksei commented on package.json
> +    "@types/js-cookie": "^3.0.3",
почистил куки и локалсторедж, и перебросило на auth, но всё равно, так быть не должно

2023-03-25 19:54 UTC, ValadzkoAliaksei commented on src/api/api.ts
> +import Cookies from 'js-cookie';
![image](https://user-images.githubusercontent.com/61273546/227737296-c139dd46-a7fb-4197-b855-a523eccb0a2d.png)
если аватарки нет, то должен быть котик рисованный. см. задание на последний спринт

2023-03-25 19:54 UTC, ValadzkoAliaksei commented on package.json
> +    "js-cookie": "^3.0.1",
![image](https://user-images.githubusercontent.com/61273546/227737331-76a42f80-3958-44b7-b881-71b9cd6fc8bf.png)
при перезагрузке страницы 2 запроса за категориями почему то идут(

2023-03-25 19:54 UTC, ValadzkoAliaksei commented on src/pages/profile/profile.tsx
> +export const Profile: FC = () => {
![image](https://user-images.githubusercontent.com/61273546/227737410-57a58349-3eae-4356-a1a3-7d2fec570eae.png)
смог выбрать 25 ноября  2022 года и отправить запрос)

2023-03-25 19:54 UTC, ValadzkoAliaksei commented on src/pages/profile/profile.tsx
> +  const dispatch = useAppDispatch();
![image](https://user-images.githubusercontent.com/61273546/227737483-eb4644fa-700a-4139-be49-ddee9b1610ba.png)
если выбрать книгу по id, то тоже почему то 2 запроса за категориями(

2023-03-25 19:54 UTC, ValadzkoAliaksei commented on src/pages/profile/profile.tsx
> +  const [isEditType, setIsEditType] = useState<boolean>(false);
![image](https://user-images.githubusercontent.com/61273546/227737525-561e5274-aed6-4a4a-a348-f57137932c8e.png)
кол-во отзывов не считает(

2023-03-25 19:54 UTC, ValadzkoAliaksei commented on src/pages/profile/profile.tsx
> +  const reservedBook = useTypedSelector(selectReservedBook) || null;
![image](https://user-images.githubusercontent.com/61273546/227737834-f677bcd0-63e7-4d8e-bf09-202e02e1f244.png)
можно отправить коммент без рейтинга и падает запрос на беке

2023-03-25 19:54 UTC, ValadzkoAliaksei commented on src/pages/profile/profile.tsx
> +  const historyBooks = useTypedSelector(selectHistoryBooks) || [];
![image](https://user-images.githubusercontent.com/61273546/227737912-0b214dfb-b2ae-44c2-ae61-68132460816d.png)
что-то котик у меня совсем не грузится(

2023-03-25 19:54 UTC, ValadzkoAliaksei commented on src/pages/profile/profile.tsx
> +  const { isError, isSuccess, toastType, user } = useTypedSelector(({ user }) => user);
![image](https://user-images.githubusercontent.com/61273546/227737944-72e5cc29-9657-473e-8b04-0a8e94006e23.png)
поля должны быть предзапорлнены данными которые прилетают с пользователем

2023-03-25 19:54 UTC, ValadzkoAliaksei commented on src/pages/profile/profile.tsx
> +    isError: isErrorBooking,
очень странный лоадер 
![image](https://user-images.githubusercontent.com/61273546/227738176-ca667388-e896-4369-b6d2-cedd94fb3705.png)

2023-03-25 19:54 UTC, ValadzkoAliaksei commented on src/pages/profile/profile.tsx
> +    isSuccess: isSuccessBooking,
валидация в профиле странна работает. если ничего не вводить и сразц нажать сохранить изменения, то все дергается  и то пропадает то появляется.

2023-03-25 19:54 UTC, ValadzkoAliaksei commented on src/pages/profile/profile.tsx
> +  } = useTypedSelector(({ booking }) => booking);
![image](https://user-images.githubusercontent.com/61273546/227738430-7b0b8719-1009-4700-9418-f75ebe10d847.png)
отзывы должны сортироваться от нового  к старому, а не наоборот

2023-03-25 19:54 UTC, ValadzkoAliaksei commented on src/pages/profile/profile.tsx
> +  const {
![image](https://user-images.githubusercontent.com/61273546/227738503-76ab9157-eddb-4dc8-8de7-f273294e5ad7.png)
изменение отзыва со страницы профиля, не подкидывает данные о старом отзыве

2023-03-25 19:54 UTC, ValadzkoAliaksei commented on src/pages/profile/profile.tsx
> +    isSuccess: isSuccessRate,
![image](https://user-images.githubusercontent.com/61273546/227738599-b540afd9-bcc6-412d-9dda-e2840b16afdf.png)
изменение отзыва не работает со страницы профиля. подставляет id книги вместо id отзыва

2023-03-25 20:08 UTC, tsakunova commented on src/pages/profile/profile.tsx
> +  const historyBooks = useTypedSelector(selectHistoryBooks) || [];
т.е. нужно обработать случай когда в image не null, а ломаная ссылка? потому что нет котика в ломаной ссылке(Алексей в чате писал что удалил фото все что народ позагружал и вот после этого в тестах пропала картинка при смене аватара - но ссылка там есть, просто по ней картинки нет)

2023-03-25 20:15 UTC, Rastamanby commented
#  Результаты тестов
Процент пройденных тестов: 97%.
Общее количество тестов: 98.
Количество непройденных тестов: 2.
***
**1-slider-no-photo-1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/tsakunova/1679775338/1-slider-no-photo-1440px.png)
***
**1-slider-no-photo-320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/tsakunova/1679775338/1-slider-no-photo-320px.png)
***
**10-app-burger-menu-close-click-not-burger-menu-768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/tsakunova/1679775338/10-app-burger-menu-close-click-not-burger-menu-768px.png)
***
**11-app-320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/tsakunova/1679775338/11-app-320px.png)
***
**12-app-burger-menu-open-320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/tsakunova/1679775338/12-app-burger-menu-open-320px.png)
***
**13-app-burger-menu-close-320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/tsakunova/1679775338/13-app-burger-menu-close-320px.png)
***
**14-app-burger-menu-close-click-not-burger-menu-320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/tsakunova/1679775338/14-app-burger-menu-close-click-not-burger-menu-320px.png)
***
**15-1440-profile-page.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/tsakunova/1679775338/15-1440-profile-page.png)
***
**16-768-profile-page.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/tsakunova/1679775338/16-768-profile-page.png)
***
**17-320-profile-page.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/tsakunova/1679775338/17-320-profile-page.png)
***
**18-profile-avatar-before.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/tsakunova/1679775338/18-profile-avatar-before.png)
***
**19-profile-avatar-after.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/tsakunova/1679775338/19-profile-avatar-after.png)
***
**2-slider-one-photo-1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/tsakunova/1679775338/2-slider-one-photo-1440px.png)
***
**2-slider-one-photo-768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/tsakunova/1679775338/2-slider-one-photo-768px.png)
***
**20-1440-profile-empty-card.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/tsakunova/1679775338/20-1440-profile-empty-card.png)
***
**21-1440-profile-empty-card.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/tsakunova/1679775338/21-1440-profile-empty-card.png)
***
**22-1440-profile-empty-card.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/tsakunova/1679775338/22-1440-profile-empty-card.png)
***
**23-1440-profile-expider-card.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/tsakunova/1679775338/23-1440-profile-expider-card.png)
***
**24-1440-profile-empty-card.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/tsakunova/1679775338/24-1440-profile-empty-card.png)
***
**25-1440-history.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/tsakunova/1679775338/25-1440-history.png)
***
**3-slider-more-two-photo-1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/tsakunova/1679775338/3-slider-more-two-photo-1440px.png)
***
**3-slider-more-two-photo-768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/tsakunova/1679775338/3-slider-more-two-photo-768px.png)
***
**4-slider-before-1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/tsakunova/1679775338/4-slider-before-1440px.png)
***
**4-slider-before-320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/tsakunova/1679775338/4-slider-before-320px.png)
***
**4-slider-before-768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/tsakunova/1679775338/4-slider-before-768px.png)
***
**5-slider-after-1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/tsakunova/1679775338/5-slider-after-1440px.png)
***
**6-app-1440.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/tsakunova/1679775338/6-app-1440.png)
***
**7-app-768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/tsakunova/1679775338/7-app-768px.png)
***
**8-app-burger-menu-open-768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/tsakunova/1679775338/8-app-burger-menu-open-768px.png)
***
**9-app -burger-menu-close-768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/tsakunova/1679775338/9-app%20-burger-menu-close-768px.png)
***
**Sprint 4 -- search and sort -- bread crumbs -- desktop -- transfer from all books category to book page (failed).png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/tsakunova/1679775338/Sprint%204%20--%20search%20and%20sort%20--%20bread%20crumbs%20--%20desktop%20--%20transfer%20from%20all%20books%20category%20to%20book%20page%20(failed).png)
***
**Sprint 4 -- search and sort -- bread crumbs -- desktop -- transfer from programming category to book page (failed).png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/tsakunova/1679775338/Sprint%204%20--%20search%20and%20sort%20--%20bread%20crumbs%20--%20desktop%20--%20transfer%20from%20programming%20category%20to%20book%20page%20(failed).png)

2023-03-25 20:19 UTC, tsakunova commented on src/pages/profile/profile.tsx
> +  const [isEditType, setIsEditType] = useState<boolean>(false);
<img width="209" alt="image" src="https://user-images.githubusercontent.com/55032592/227739636-a38d9e8b-a650-4202-b1c3-3fd36298c25e.png">
 не понятно почему я их вижу(((

2023-03-25 20:24 UTC, tsakunova commented on src/pages/profile/profile.tsx
> +    isSuccess: isSuccessRate,
<img width="442" alt="image" src="https://user-images.githubusercontent.com/55032592/227739774-d7169dea-1567-4954-9159-00b88738c525.png">
<img width="572" alt="image" src="https://user-images.githubusercontent.com/55032592/227739787-e384938b-53b4-4004-9a99-fd99418e030c.png">
Не могу понять почему у меня меняется и подставляется текст и оценка из отзывы((((

2023-03-26 00:49 UTC, ValadzkoAliaksei commented on src/pages/profile/profile.tsx
> +    isSuccess: isSuccessRate,
я ж написал, из страницы профиля, а вы страницу книги по id показываете)

2023-03-26 12:33 UTC, ValadzkoAliaksei commented on package.json
> +    "@types/js-cookie": "^3.0.3",
мои комменты все еще актуалыны

2023-03-26 12:45 UTC, tsakunova commented on package.json
> +    "@types/js-cookie": "^3.0.3",
Да, я в процессе)) перекраиваю поведение модалок и запросы

2023-03-26 22:37 UTC, Rastamanby commented
#  Результаты тестов
Процент пройденных тестов: 100%.
Общее количество тестов: 98.
Количество непройденных тестов: 0.
***
**1-slider-no-photo-1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/tsakunova/1679870251/1-slider-no-photo-1440px.png)
***
**1-slider-no-photo-320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/tsakunova/1679870251/1-slider-no-photo-320px.png)
***
**10-app-burger-menu-close-click-not-burger-menu-768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/tsakunova/1679870251/10-app-burger-menu-close-click-not-burger-menu-768px.png)
***
**11-app-320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/tsakunova/1679870251/11-app-320px.png)
***
**12-app-burger-menu-open-320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/tsakunova/1679870251/12-app-burger-menu-open-320px.png)
***
**13-app-burger-menu-close-320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/tsakunova/1679870251/13-app-burger-menu-close-320px.png)
***
**14-app-burger-menu-close-click-not-burger-menu-320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/tsakunova/1679870251/14-app-burger-menu-close-click-not-burger-menu-320px.png)
***
**15-1440-profile-page.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/tsakunova/1679870251/15-1440-profile-page.png)
***
**16-768-profile-page.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/tsakunova/1679870251/16-768-profile-page.png)
***
**17-320-profile-page.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/tsakunova/1679870251/17-320-profile-page.png)
***
**18-profile-avatar-before.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/tsakunova/1679870251/18-profile-avatar-before.png)
***
**19-profile-avatar-after.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/tsakunova/1679870251/19-profile-avatar-after.png)
***
**2-slider-one-photo-1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/tsakunova/1679870251/2-slider-one-photo-1440px.png)
***
**2-slider-one-photo-768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/tsakunova/1679870251/2-slider-one-photo-768px.png)
***
**20-1440-profile-empty-card.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/tsakunova/1679870251/20-1440-profile-empty-card.png)
***
**21-1440-profile-empty-card.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/tsakunova/1679870251/21-1440-profile-empty-card.png)
***
**22-1440-profile-empty-card.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/tsakunova/1679870251/22-1440-profile-empty-card.png)
***
**23-1440-profile-expider-card.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/tsakunova/1679870251/23-1440-profile-expider-card.png)
***
**24-1440-profile-empty-card.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/tsakunova/1679870251/24-1440-profile-empty-card.png)
***
**25-1440-history.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/tsakunova/1679870251/25-1440-history.png)
***
**3-slider-more-two-photo-1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/tsakunova/1679870251/3-slider-more-two-photo-1440px.png)
***
**3-slider-more-two-photo-768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/tsakunova/1679870251/3-slider-more-two-photo-768px.png)
***
**4-slider-before-1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/tsakunova/1679870251/4-slider-before-1440px.png)
***
**4-slider-before-320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/tsakunova/1679870251/4-slider-before-320px.png)
***
**4-slider-before-768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/tsakunova/1679870251/4-slider-before-768px.png)
***
**5-slider-after-1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/tsakunova/1679870251/5-slider-after-1440px.png)
***
**6-app-1440.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/tsakunova/1679870251/6-app-1440.png)
***
**7-app-768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/tsakunova/1679870251/7-app-768px.png)
***
**8-app-burger-menu-open-768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/tsakunova/1679870251/8-app-burger-menu-open-768px.png)
***
**9-app -burger-menu-close-768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/tsakunova/1679870251/9-app%20-burger-menu-close-768px.png)

2023-03-27 04:21 UTC, vvikota approved these changes

2023-03-27 05:04 UTC, tsakunova commented on package.json
> +    "@types/js-cookie": "^3.0.3",
@ValadzkoAliaksei все замечания исправлены ✅

2023-03-27 10:39 UTC, ValadzkoAliaksei approved these changes

2023-03-27 10:40 UTC, merged